In [9]:
import numpy as np

In [11]:
arr=np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[8]

8

In [17]:
arr[4:6]

array([4, 5])

In [19]:
arr[1:5]

array([1, 2, 3, 4])

In [21]:
arr[:5]

array([0, 1, 2, 3, 4])

In [23]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[0:5]=100

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
arr=np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
slice_of_arr=arr[0:6]

In [35]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
slice_of_arr[:]=99

In [39]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
#using double brakets 
arr_2d[1][1]

25

In [65]:
arr_2d[2][1]

40

In [67]:
arr_2d[1,2]

30

In [71]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [75]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr=np.arange(1,11)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
bool_arr=arr>5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [95]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [97]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [99]:
arr[arr<3]

array([1, 2])

### Numpy Operations

In [102]:
## Array with array
import numpy as np


In [104]:
arr=np.arange(0,11)

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [110]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])